services:
  simplifyqa-pipeline-executor:
    container_name: simplifyqa-pipeline-executor
    # image: bernardbdas/simplifyqa-pipeline-executor:latest
    image: simplifyqa-pipeline-executor
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false