name: SimplifyQA Pipeline Executor Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]
  workflow_dispatch:
    inputs:
      runner:
        description: 'Select Runner'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - self-hosted

jobs:
  build-test:
    runs-on: [ "ubuntu-latest", "${{ inputs.runner }}" ]
    steps:
    -
      name: Checkout Source Code
      uses: actions/checkout@v4
      with:
       repository: ${{ vars.GIT_USERNAME }}/${{ vars.REPO_NAME }}
       token: ${{ secrets.REPO_TOKEN }}
    - 
      name: Build using NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
  deploy:
    runs-on: [ "ubuntu-latest", "${{ inputs.runner }}" ]
    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: user/app:latest
